---
title: "Read quality check"
output:
  beamer_presentation:
    latex_engine: xelatex
---

```{r setup, include = FALSE}
library(magrittr)
library(tidyverse)
library(glue)
library(Biostrings)
library(ShortRead)
library(ggplot2)
library("scales")
library(drake)
source(here::here("scripts", "qstats.R"))
source(here::here("scripts", "output_functions.R"))
knitr::opts_chunk$set(echo = FALSE, device = "tikz")
theme_set(theme_bw(base_size = 24) + theme(legend.direction = "vertical"))
```

```{r include=FALSE}
datasets <- readd(datasets)
# xdata <- readd(itsxtrim_.its1.lr5.)
# pos <- readd(positions_pb500002A1f)
reads <- readd(parsed_qstat) %>%
  dplyr::group_by(seq_run, region, step, stat, value, region, read) %>%
  dplyr::summarize_at("nreads", sum) %>%
  dplyr::ungroup() %>%
  dplyr::mutate_at(
    "region",
    factor,
    levels = c(NA, "ITS2", "ITS1", "5_8S", "LSU1", "LSU2", "LSU3", "LSU4", "D1", "D2", "D3", "short", "ITS", "LSU", "32S", "long")
  ) %>%
  dplyr::left_join(
    dplyr::select(datasets, dataset, seq_run, tech, machine, amplicon),
    by = "seq_run"
  ) %>%
  dplyr::mutate_at(
    "dataset", factor,
    levels = c("short-ion", "short-illumina", "short-pacbio", "long-pacbio")
  ) %>%
  tidyr::replace_na(list(read = "")) %>%
  dplyr::mutate(`Read type` = paste(tech, amplicon, substr(read, 2, 3)) %>%
                  trimws())
```

## Minimum quality score -- strategies

```{r}
dplyr::filter(reads, stat == "minq", step == "raw") %>%
  dplyr::arrange(value) %>%
  dplyr::group_by(`Read type`) %>%
  dplyr::mutate(ecdf = 1 - cumsum(nreads)/sum(nreads)) %>%
  ggplot(aes(x = value,
             y = ecdf,
             linetype = `Read type`,
             group = `Read type`,
             color = `Read type`)) +
  geom_line() +
  scale_x_continuous(name = "Minimum quality score",
                     # trans = reverselog_trans(10),
                     # limits = c(NA, 1e-5),
                     oob = squish) +
  scale_y_continuous(name = "Fraction passing") +
  scale_color_read() +
  scale_linetype_discrete()
```

## Minimum quality score -- regions

```{r}
dplyr::filter(reads, stat == "minq", step == "lsux", amplicon == "Long",
              region %in% c("ITS1", "ITS2", "5_8S", "ITS", "LSU", "long")) %>%
  dplyr::arrange(value) %>%
  dplyr::group_by(region) %>%
  dplyr::mutate(ecdf = 1 - cumsum(nreads)/sum(nreads)) %>%
  ggplot(aes(x = value,
             y = ecdf,
             linetype = region,
             group = region,
             color = region)) +
  geom_line() +
  scale_x_continuous(name = "Minimum quality score",
                     # trans = reverselog_trans(10),
                     # limits = c(NA, 1e-5),
                     oob = squish) +
  scale_y_continuous(name = "Fraction passing") +
  scale_color_viridis_d(end = 0.95) +
  scale_linetype_discrete()
```

## Expected error rate --strategies

```{r}
erate_plot <- dplyr::filter(reads, stat == "erate", step == "raw") %>%
  dplyr::arrange(value) %>%
  dplyr::group_by(`Read type`) %>%
  dplyr::mutate(ecdf = cumsum(nreads)/sum(nreads)) %>%
  ggplot(aes(x = value,
             y = ecdf,
             linetype = `Read type`,
             group = `Read type`,
             color = `Read type`)) +
  geom_line() +
  scale_x_continuous(name = "Expected error-rate",
                     trans = reverselog_trans(10),
                     limits = c(NA, 1e-5),
                     oob = squish) +
  scale_y_continuous(name = "Fraction passing") +
  scale_color_read(guide = guide_legend(title = NULL, ncol = 2)) +
  scale_linetype_discrete(guide = guide_legend(title = NULL, ncol = 2)) +
  theme(legend.position = "bottom")
erate_plot
```

## Expected number of errors --strategies

```{r}
eexp_plot <- dplyr::filter(reads, stat == "eexp", step == "raw") %>%
  dplyr::arrange(value) %>%
  dplyr::group_by(`Read type`) %>%
  dplyr::mutate(ecdf = cumsum(nreads)/sum(nreads)) %>%
  ggplot(aes(x = value,
             y = ecdf,
             linetype = `Read type`,
             group = `Read type`,
             color = `Read type`)) +
  geom_vline(xintercept = 3, linetype = "dashed", color = "gray50") +
  geom_line() +
  scale_x_continuous(name = "Expected number of errors",
                     trans = reverselog_trans(10),
                     limits = c(NA, 0.1),
                     oob = squish) +
  scale_y_continuous(name = "Fraction passing") +
  scale_color_read(guide = guide_legend(title = NULL, ncol = 2)) +
  scale_linetype_discrete(guide = guide_legend(title = NULL, ncol = 2)) +
  theme(legend.position = "bottom")
eexp_plot
```

## Per-base and per-read error rate -- strategies

```{r}
ggpubr::ggarrange(erate_plot, eexp_plot, ncol = 1, common.legend = TRUE,
                  legend = "bottom", labels = "auto")
```


## Error-free probability --strategies

```{r}
dplyr::filter(reads, stat == "p.noerr", step == "raw") %>%
  dplyr::arrange(dplyr::desc((value))) %>%
  dplyr::group_by(`Read type`) %>%
  dplyr::mutate(ecdf = cumsum(nreads)/sum(nreads)) %>%
  ggplot(aes(x = value,
             y = ecdf,
             linetype = `Read type`,
             group = `Read type`,
             color = `Read type`)) +
  geom_line() +
  scale_x_continuous(name = "Expectation of being error-free",
                     # trans = log_trans(10),
                     limits = c(0, 1),
                     oob = squish) +
  scale_y_continuous(name = "Fraction passing") +
  scale_color_read() +
  scale_linetype_discrete()
```

## Read length -- strategies

```{r}
dplyr::filter(reads, stat == "length", step == "raw") %>%
  dplyr::arrange(value) %>%
  dplyr::group_by(`Read type`) %>%
  dplyr::mutate(ecdf = 1 - cumsum(nreads)/sum(nreads)) %>%
  ggplot(aes(x = value,
             y = ecdf,
             linetype = `Read type`,
             group = `Read type`,
             color = `Read type`)) +
  geom_line() +
  scale_x_log10(name = "Length (bp)",
                limits = c(50, NA),
                oob = squish) +
  scale_y_continuous(name = "Fraction Greater than length") +
  scale_color_viridis_d(option = "C", end = 0.9) +
  scale_linetype_discrete()
```

## Read length density
```{r}
dplyr::filter(reads, stat == "erate", step == "raw") %>%
  dplyr::arrange(value) %>%
  dplyr::group_by(`Read type`) %>%
  dplyr::mutate(ecdf = cumsum(nreads)/sum(nreads)) %>%
  ggplot(aes(x = value,
             y = ecdf,
             linetype = `Read type`,
             group = `Read type`,
             color = `Read type`)) +
  geom_line() +
  scale_x_log10(name = "Length (bp)",
                limits = c(50, NA),
                oob = squish) +
  scale_y_continuous(name = "count") +
  scale_color_viridis_d(option = "C") +
  scale_linetype_discrete()
```

## Expected error-free reads
```{r}
reads %>%
  dplyr::filter(step %in% c("raw", "lsux"), stat == "p.noerr") %>%
  group_by(dataset, read, region) %>%
  summarize(`Expected Error-Free` = sum(value * nreads),
            Total = sum(nreads)) %>%
  knitr::kable()
```
