buildtype: 'local'

rdir:        'scripts'
makelocarna: 'scripts/snakemakelocarna.sh'
switchreads: 'scripts/switch_reads.sh'

rawdir: 'raw_data'

seqdir:    'sequences'
moviedir:  'sequences/rawmovie'
ccsdir:    'sequences/ccs'
fastqdir:  'sequences/rawfastq'
demuxdir:  'sequences/demux'
trimdir:   'sequences/trim'
regiondir: 'sequences/regions'
filterdir: 'sequences/filter'

datadir:            'data'
clusterdir:         'data/clusters'
locarnadir:         'data/mlocarna'
cmaln_long:         'data/mlocarna/long_cmalign.aln'
guide_tree:         'data/mlocarna/32S_guide.tree'
mlocarna_pp_dir:    'data/mlocarna/consensus_pp'
mlocarna_dir:       'data/mlocarna/consensus'
mlocarna_aln:       'data/mlocarna/consensus/results/result.stk'
raxml_dir:          'data/raxml'
pastadir:           'data/pasta'
plandir:            'data/plan'
drakedata:          'data/plan/drake.Rdata'
demux_file:         'data/plan/demux_hash.dat'

labdir:     'config'
tagdir:     'config/tags'
dataset:    'config/datasets.csv'
regions:    'config/regions.csv'
methods:    'config/taxonomy_methods.csv'
platemap:   'config/Brendan_soil2.xlsx'
gits7_tags: 'config/Hectors_tag_primer_plates.xlsx'
lr5_tags:   'config/Brendan_soil2.xlsx'

configdir:           'config'
condadir:            'config/conda'
makelocarna_profile: 'config/snakemakelocarnaUPPMAX'
makelocarna_conda:   'config/snakemakelocarna.yaml'

rmddir: 'writing'
outdir: 'output'
logdir: 'logs'

ref_root: 'reference'
cm_5_8S:  'reference/RF00002.cm'
cm_32S:   'reference/fungi_32S_LR5.cm'

platemap_sheet: 'Concentration samples'
bigsplit: 80
smallsplit: 12
ropt: '--no-save --no-environ --no-restore'

reannotate_url: 'github.com/brendanf/reannotate/releases/download/v0.1'