rdir: 'scripts'
rawdir: 'raw_data'
seqdir: 'sequences'
datadir: 'data'
labdir: 'config'
rmddir: 'writing'
outdir: 'output'
logdir: 'logs'
ref_root: 'reference'
ROPT: '--no-save --no-environ --no-restore'
RARGS: '--bootstrap-packrat'
