name: dev
channels:
  - conda-forge
  - bioconda
  - defaults
  - bfurneaux
dependencies:
  - r-base=3.5.1
  # R utility
  - r-tidyverse=1.2.1
  - r-tidyr>=1.0.0
  - r-here=0.1
  - r-tidyxl=1.0.4
  - r-glue=1.3.1
  - r-assertr=2.6
  # Drake and friends
  - r-drake=7.8.0
  - r-fst
  - r-disk.frame
  - r-clustermq=0.8.8
  - r-visnetwork=2.0.9
  - r-networkd3=0.4
  - r-tictoc=1.0
  # R Bioinformatics
  - r-seqinr=3.6_1
  - r-rcppparallel=4.4.4
  - r-phytools=0.6
  - r-phylobase=0.8.6
  - r-taxa=0.3.2
  - r-taxize=0.9.91
  - r-castor=1.5.5
  - r-stringdist=0.9.5
  - bioconductor-decipher=2.10.0
  - bioconductor-phyloseq=1.26.0
  - r-rgbif=1.3.0
  - r-gstat=2.0
  - r-dada2=1.12.1
  - r-tzara=0.0.7.8
  - r-funguildr=0.1
  - r-tikzdevice=0.12
  - r-inext=2.0.19
  - r-ips=0.0.11
  - r-reldist=1.6
  - r-deming=1.4
  # external tools
  - infernal=1.1.2
  - vsearch=2.9.1
  - locarna=2.0.0
  - raxml=8.2.12
  - epa-ng=0.3.6
  - gappa=0.5.1
  - mafft=7.453
  - samtools
  - snakemake-minimal=5.5.4
  - pandas=0.25.1
  # Plotting
  - r-ggpubr
  - r-ggnomics
  - bioconductor-ggtree
  - r-eulerr
  - r-metacoder
  # Knitting
  - r-bookdown
  - r-kableextra  
  # Rstudio and development tools
  - rstudio
  - defaults::qt
  - r-mcmcglmm
  - r-lme4
  - r-pdftools
  - r-lintr
  - r-roxygen2
  - r-devtools
  - r-pryr
  - r-usethis
