name: dev
channels:
  - conda-forge
  - bioconda
  - defaults
  - bfurneaux
dependencies:
  - r-base
  - r-tidyverse
  - r-stringi=1.4.4
  - r-here
  - r-clustermq
  - r-tidyxl
  - r-glue
  - r-seqinr
  - r-visnetwork
  - r-networkd3
  - r-tictoc
  - r-rcppparallel
  - r-phytools
  - r-phylobase
  - r-taxa
  - r-taxize
  - r-castor
  - r-stringdist
  - bioconductor-odseq
  - bioconductor-decipher
  - bioconductor-phyloseq
  - r-rgbif
  - r-gstat
  - bioconductor-dada2
  - r-tzara=0.0.7.8
  - r-funguildr=0.1
  - r-drake=7.8.0
  - r-fst
  - r-disk.frame
  - r-assertr
  - r-tikzdevice
  - r-inext
  - r-ips
  - r-reldist
  - infernal=1.1.2
  - locarna=2.0.0
  - raxml=8.2.12
  - epa-ng=0.3.6
  - gappa=0.5.1
  - mafft=7.453
  - snakemake-minimal=5.5.4
  - pandas=0.25.1
  - rdonnely:rstudio
  - r-bookdown
  - r-ggpubr
  - r-kableextra
  - r-eulerr
  - bioconductor-ggtree
  - r-metacoder=0.3.3
  - r-pdftools
  - r-lintr
  - r-devtools
  - r-roxygen2
  - r-pryr
  - r-usethis
