name: dev
channels:
  - conda-forge
  - bioconda
  - defaults
  - bfurneaux
dependencies:
  - r-base
  - r-tidyverse
  - r-tidyr
  - r-here
  - r-clustermq
  - r-tidyxl
  - r-glue
  - r-bookdown
  - r-ggpubr
  - r-seqinr
  - r-visnetwork
  - r-networkd3
  - r-tictoc
  - r-rcppparallel
  - r-phytools
  - r-phylobase
  - r-taxa
  - r-taxize
  - r-castor
  - r-stringdist
  - bioconductor-odseq
  - bioconductor-decipher
  - bioconductor-phyloseq
  - bioconductor-ggtree
  - r-metacoder
  - r-rgbif
  - r-gstat
  - r-dada2
  - r-tzara
  - r-ritsx
  - r-funguildr
  - r-drake
  - r-fst
  - r-disk.frame
  - r-assertr
  - r-tikzdevice
  - r-inext
  - r-ips
  - r-usethis
  - r-reldist
  - r-kableextra
  - r-eulerr
  - rstudio
  - r-lintr
  - r-roxygen2
  - r-devtools
  - r-pdftools
  - r-pryr
  - infernal
  - locarna
  - raxml
  - epa-ng
  - gappa
  - mafft
  - itsx
  - defaults::qt
  - snakemake-minimal
  - pandas
