name: drake
channels:
  - conda-forge
  - bioconda
  - defaults
  - bfurneaux
dependencies:
  - r-base=3.5.1
  - r-tidyverse=1.2.1
  - r-tidyr>=1.0.0
  - r-here=0.1
  - r-clustermq=0.8.8
  - r-tidyxl=1.0.4
  - r-glue=1.3.1
  - r-bookdown=0.9
  - r-seqinr=3.4_5
  - r-visnetwork=2.0.6
  - r-networkd3=0.4
  - r-tictoc=1.0
  - r-rcppparallel=4.4.2
  - r-phytools=0.6
  - r-phylobase=0.8.4
  - r-taxa=0.3.2
  - r-castor=1.3.5
  - r-stringdist=0.9.5
  - bioconductor-odseq=1.10.0
  - bioconductor-decipher=2.10.0
  - bioconductor-phyloseq=1.26.0
  - bioconductor-ggtree=1.14.4
  - r-rgbif=1.3.0
  - r-dada2=1.12.1
  - r-tzara=0.0.7.8
  - r-ritsx=0.0.3
  - r-funguildr=0.1
  - r-drake=7.7.0.9002=r35_2
  - r-fst=0.9.0
  - r-disk.frame=0.2.0
  - r-assertr=2.6
  - r-tikzdevice=0.12
  - r-inext=2.0.19
  - r-ips=0.0.11
  - r-usethis=1.5.0
  - infernal=1.1.2
  - itsx=1.1b
  - vsearch=2.9.1
  - locarna=2.0.0
  - raxml=8.2.12
  - epa-ng=0.3.6
  - snakemake-minimal=5.5.4
  - pandas=0.25.1
