jobs: 9999
keep-going: True
immediate-submit: True
notemp: True
jobscript: "slurm-jobscript.sh"
cluster: "slurm-submit.py --dependency \"afterok:{dependencies}\""
cluster-status: "slurm-status.py"
max-jobs-per-second: 10
max-status-checks-per-second: 10
cluster-config: "UPPMAX.yaml"

